package fr.donovan.spotifish.mapping;

public interface UserLikeableItemUrlRoute {

    String URL_USERLIKEABLEITEM = "/userlikeableitem";
    String URL_USERLIKEABLEITEM_NEW = URL_USERLIKEABLEITEM + "/new";
    String URL_USERLIKEABLEITEM_EDIT = URL_USERLIKEABLEITEM + "/edit";
    String URL_USERLIKEABLEITEM_DELETE = URL_USERLIKEABLEITEM + "/delete";

    String URL_ADMIN_USERLIKEABLEITEM = "/admin" + URL_USERLIKEABLEITEM;
    String URL_ADMIN_USERLIKEABLEITEM_NEW = URL_ADMIN_USERLIKEABLEITEM + "/new";
    String URL_ADMIN_USERLIKEABLEITEM_EDIT = URL_ADMIN_USERLIKEABLEITEM + "/edit";
    String URL_ADMIN_USERLIKEABLEITEM_DELETE = URL_ADMIN_USERLIKEABLEITEM + "/delete";
}